# Generated by Django 4.0.5 on 2022-06-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ur', 'Urdu')], default='en', max_length=32),
        ),
    ]
