START_COMMAND = "/start"

SUBSCRIBE_COMMAND = "/subscribe"

LANGUAGE_COMMAND = "/language"

SUPPORTED_LANGUAGES = {"en": "ENGLISH", "ur": "URDU"}

SUPPORTED_COMMANDS = {START_COMMAND, SUBSCRIBE_COMMAND, LANGUAGE_COMMAND}
